### ISSUE TITLE
Update events not reported if not manually executed via WP Admin

### ISSUE THREAD

**Issue by deepdivingspearo** [TheJester12/wp-client-reports#2]
Hello,
Thanks for the work on this plugin. 
I think I may have discovered a bug. 
I manage a lot of WP sites and run weekly updates etc for my clients. You can see why I thought you plugin may be useful :)
I use InfiniteWP to manage updates. It would seem that is I run updates via my InfiniteWP control panel, the plugin does not register the updates. None of the updates I ran this week are showing after installing the reporting plugin last week on the sites.
Thanks in advance.
Regards
Brendan

**Comment by deepdivingspearo** [comment]
Just a follow-up. It seems the events ARE captured, but not immediately. So my experience is as follows;

1. run updates via InfiniteWP
2. review reports, within an hour of doing the updates - activity not logged
3. review several days later, in this case the following Monday after running the updates on a Friday - activity is captured and reported.

**Comment by TheJester12** [comment]
The plugin uses several methods to capture updates:

1. You can manually run a check for plugin updates
2. It tries to use the WordPress hook that happens after a plugin update
3. It checks once a day to see if there are any uncaptured updates.

I can imagine that using a plugin like Inifinity may not run the WordPress hook I mentioned above. In that case you can run a manual check if you'd like.
